### ISSUE TITLE
Cannot read property 'site' of undefined

### ISSUE THREAD

**Issue by mibac138** [TheIoTCrowd/StackPostTimer#4] opened 2017-08-06 19:37 UTC
#### Browser name, version and operating system: 

Chrome 60 on Windows

#### StackTimer version:
 

0.3.0

#### Description:

Sometimes the script fails with the following error: 
```
ERROR: Execution of script 'Stack Exchange Timer' failed! Cannot read property 'site' of undefined
(anonymous) @ VM2794:3
(anonymous) @ VM2794:4
(anonymous) @ VM2794:23254
(anonymous) @ VM2786:2
E_c @ VM2786:3
E @ VM2791:58
create @ VM2791:67
e @ VM2791:15
run @ VM2791:15
(anonymous) @ VM2791:68
(anonymous) @ VM2786:2
b @ VM2786:2
(anonymous) @ VM2791:68
(anonymous) @ VM2791:68
TM_back @ VM2791:69
(anonymous) @ VM2791:69
(anonymous) @ VM2786:2
exec_fn @ VM2786:1
(anonymous) @ VM2786:11
aa @ VM2786:9
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:26
(anonymous) @ content.js:24
sendResponseAndClearCallback @ VM2762 extensions::messaging:366
messageListener @ VM2762 extensions::messaging:398
EventImpl.dispatchToListener @ VM2755 extensions::event_bindings:380
publicClassPrototype.(anonymous function) @ VM2761 extensions::utils:149
EventImpl.dispatch_ @ VM2755 extensions::event_bindings:364
EventImpl.dispatch @ VM2755 extensions::event_bindings:386
publicClassPrototype.(anonymous function) @ VM2761 extensions::utils:149
dispatchOnMessage @ VM2762 extensions::messaging:339
```

#### Steps to reproduce:

Hard to say, I've done it [here](https://gaming.stackexchange.com/questions/315335/is-it-possible-to-hit-a-mine-on-first-click). Basically try to reload the site a bunch of times and it should appear

**Comment by TheIoTCrowd** [comment] 2017-08-19 09:26
I'm guessing this is a dupe of #5. What I *think* is happening:

- The script sometimes loads earlier than the rest of the page, in particular the `StackExchange` object that the site provides in JavaScript
- If `StackExchange` is not declared by the time this script runs, it just crashes completely.

I'll see if I can confirm this theory and fix it.

**Closed as completed** 2017-08-19 09:40 UTC
Labels: bug, completed

**Comment by TheIoTCrowd** [comment] 2017-08-19 09:42
I just reproduced the issue, and changing the time that the script runs seems to resolve this. Let me know if you spot this after patch 0.3.1 goes out—if you do find the issue again, I can reopen this.
